baseURL = "https://example.org/"
relativeURL = "true"
languageCode = "en-us"


theme = "arcana"
copyright = "© Untitled. All rights reserved"

defaultContentLanguage = "en"
[languages]
    [languages.en]
        languageName = "English"
        weight = 1
    [languages.de]
        languageName = "Deutsch"
        weight = 2
    [languages.es]
        languageName = "Spanish"
        weight = 3

[taxonomies]
    tag = "tags"

[markup.goldmark.renderer]
    unsafe= true

[params]
   
    show_post_dates = false

    [[params.social]]
        title = "GitHub"
        icon = "fa-github"
        url = "#"

    [params.footer]
         backgroundImage = 'images/mainPhoto.jpg'
        [[params.footer.links]]
            header = "Links to Stuff"
        [[params.footer.links.links]]
            title = "Mattis et quis rutrum"
            url = "#"
        [[params.footer.links.links]]
            title = "Suspendisse amet varius"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus quis"
            url = "#"
        [[params.footer.links.links]]
            title = "Rutrum accumsan dolor"
            url = "#"
        [[params.footer.links.links]]
            title = "Mattis rutrum accumsan"
            url = "#"
        [[params.footer.links.links]]
            title = "Suspendisse varius nibh"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus mattis"
            url = "#"

        [[params.footer.links]]
            header = "More Links to Stuff"
        [[params.footer.links.links]]
            title = "Duis neque nisi dapibus"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus quis"
            url = "#"
        [[params.footer.links.links]]
            title = "Rutrum accumsan sed"
            url = "#"
        [[params.footer.links.links]]
            title = "Mattis et sed accumsan"
            url = "#"
        [[params.footer.links.links]]
            title = "Duis neque nisi sed"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus quis"
            url = "#"
        [[params.footer.links.links]]
            title = "Rutrum amet varius"
            url = "#"
