baseURL = "https://example.org/"
relativeURL = "true"
languageCode = "en-us"


theme = "arcana"
copyright = "© PNNL. 2024"

defaultContentLanguage = "en"
[languages]
    [languages.en]
        languageName = "English"
        weight = 1
    [languages.de]
        languageName = "Deutsch"
        weight = 2
    [languages.es]
        languageName = "Spanish"
        weight = 3

[taxonomies]
    tag = "tags"

[markup.goldmark.renderer]
    unsafe= true

[params]
    show_post_dates = false
    [[params.social]]
        title = "GitHub"
        icon = "fa-github"
        url = "https://github.com/volttron/volttron"
