[[main]]
    name = "ARCHIVES"
    weight = 60
[[main]]
    parent = "ARCHIVES"
    name = "PUBLICATIONS"
    url = "/archives/publications/"
    weight = 61

[[main]]
    parent = "ARCHIVES"
    name = "PLAYLISTS"
     url = "/tags/playlists/"
    weight = 64
[[main]]
    parent = "ARCHIVES"
    name = "QUOTES"
     url = "/archives/quotes/"
    weight = 65
[[main]]
    parent = "ARCHIVES"
    name = "ACCOMPLISHMENTS"
     url = "/archives/accomplishments/"
    weight = 66
